// This file is autogenerated by the hyperschema compiler
// Schema Version: 2
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 2

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @bundlebee/resolutions
const encoding0 = c.record(c.string, c.string)

// @bundlebee/entry
const encoding1 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.source)
    encoding0.preencode(state, m.resolutions)
  },
  encode(state, m) {
    c.buffer.encode(state, m.source)
    encoding0.encode(state, m.resolutions)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = encoding0.decode(state)

    return {
      source: r0,
      resolutions: r1
    }
  }
}

// @bundlebee/manifest
const encoding2 = {
  preencode(state, m) {
    c.uint.preencode(state, m.abi)
    state.end++ // max flag is 1 so always one byte

    if (version >= 2 && m.trace) encoding2_1.preencode(state, m.trace)
  },
  encode(state, m) {
    const flags = version >= 2 && m.trace ? 1 : 0

    c.uint.encode(state, m.abi)
    c.uint.encode(state, flags)

    if (version >= 2 && m.trace) encoding2_1.encode(state, m.trace)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const flags = state.start < state.end ? c.uint.decode(state) : 0

    return {
      abi: r0,
      trace: version >= 2 && (flags & 1) !== 0 ? encoding2_1.decode(state) : null
    }
  }
}

// @bundlebee/peer-deps.packages
const encoding3_0 = c.array(c.string)

// @bundlebee/peer-deps
const encoding3 = {
  preencode(state, m) {
    encoding3_0.preencode(state, m.packages)
  },
  encode(state, m) {
    encoding3_0.encode(state, m.packages)
  },
  decode(state) {
    const r0 = encoding3_0.decode(state)

    return {
      packages: r0
    }
  }
}

// @bundlebee/trace
const encoding4 = {
  preencode(state, m) {
    c.uint.preencode(state, m.core)
    c.uint.preencode(state, m.seq)
  },
  encode(state, m) {
    c.uint.encode(state, m.core)
    c.uint.encode(state, m.seq)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)

    return {
      core: r0,
      seq: r1
    }
  }
}

// @bundlebee/manifest.trace, deferred due to recusive use
const encoding2_1 = c.array(c.frame(encoding4))

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@bundlebee/resolutions':
      return encoding0
    case '@bundlebee/entry':
      return encoding1
    case '@bundlebee/manifest':
      return encoding2
    case '@bundlebee/peer-deps':
      return encoding3
    case '@bundlebee/trace':
      return encoding4
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
