// This file is autogenerated by the hyperschema compiler
// Schema Version: 2
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 2

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @hyperbundle/resolutions
const encoding0 = c.record(c.string, c.string)

// @hyperbundle/entry
const encoding1 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.source)
    encoding0.preencode(state, m.resolutions)
  },
  encode(state, m) {
    c.buffer.encode(state, m.source)
    encoding0.encode(state, m.resolutions)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = encoding0.decode(state)

    return {
      source: r0,
      resolutions: r1
    }
  }
}

// @hyperbundle/manifest
const encoding2 = {
  preencode(state, m) {
    c.uint.preencode(state, m.abi)
  },
  encode(state, m) {
    c.uint.encode(state, m.abi)
  },
  decode(state) {
    const r0 = c.uint.decode(state)

    return {
      abi: r0
    }
  }
}

// @hyperbundle/peer-deps.packages
const encoding3_0 = c.array(c.string)

// @hyperbundle/peer-deps
const encoding3 = {
  preencode(state, m) {
    encoding3_0.preencode(state, m.packages)
  },
  encode(state, m) {
    encoding3_0.encode(state, m.packages)
  },
  decode(state) {
    const r0 = encoding3_0.decode(state)

    return {
      packages: r0
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@hyperbundle/resolutions':
      return encoding0
    case '@hyperbundle/entry':
      return encoding1
    case '@hyperbundle/manifest':
      return encoding2
    case '@hyperbundle/peer-deps':
      return encoding3
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
